[package]
name = "digimon_card_core"
version = "0.1.0"
edition = "2021"
workspace = "../digimon_card_api"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
